In [4]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# pd.read_csv("data_vegetals.csv")

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (FAO),Item,Year Code,Year,Unit,Value,Flag,Flag Description
0,FBS,Food Balances (2010-),4,Afghanistan,645,Food supply quantity (kg/capita/yr),2511,Wheat and products,2018,2018,kg,162.62,E,Estimated value
1,FBS,Food Balances (2010-),4,Afghanistan,645,Food supply quantity (kg/capita/yr),2511,Wheat and products,2019,2019,kg,160.40,E,Estimated value
2,FBS,Food Balances (2010-),4,Afghanistan,664,Food supply (kcal/capita/day),2511,Wheat and products,2018,2018,kcal/cap/d,1365.34,E,Estimated value
3,FBS,Food Balances (2010-),4,Afghanistan,664,Food supply (kcal/capita/day),2511,Wheat and products,2019,2019,kcal/cap/d,1346.93,E,Estimated value
4,FBS,Food Balances (2010-),4,Afghanistan,674,Protein supply quantity (g/capita/day),2511,Wheat and products,2018,2018,g/cap/d,41.23,E,Estimated value
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86221,FBS,Food Balances (2010-),716,Zimbabwe,664,Food supply (kcal/capita/day),2658,"Beverages, Alcoholic",2019,2019,kcal/cap/d,27.22,E,Estimated value
86222,FBS,Food Balances (2010-),716,Zimbabwe,674,Protein supply quantity (g/capita/day),2658,"Beverages, Alcoholic",2018,2018,g/cap/d,0.03,E,Estimated value
86223,FBS,Food Balances (2010-),716,Zimbabwe,674,Protein supply quantity (g/capita/day),2658,"Beverages, Alcoholic",2019,2019,g/cap/d,0.03,E,Estimated value
86224,FBS,Food Balances (2010-),716,Zimbabwe,684,Fat supply quantity (g/capita/day),2658,"Beverages, Alcoholic",2018,2018,g/cap/d,0.22,E,Estimated value
86225,FBS,Food Balances (2010-),716,Zimbabwe,684,Fat supply quantity (g/capita/day),2658,"Beverages, Alcoholic",2019,2019,g/cap/d,0.21,E,Estimated value

Quelques fonctions de bases :

df.head() : Afficher le dÃ©but de la DataFrame

df.describe() : Statistiques rapides

df.drop("columnname, columnname, ...") : Ã‰liminer certaines colonnes

df.dropna(axis=0) : Ã‰liminer les lignes aux donnÃ©es manquantes

df.["columnname"].value_counts() : Compter les rÃ©pÃ©titions

df.groupby(["columnname"]) : Analyse par groupe

On enregistre notre DataFrame sous une variable :

In [ ]:
data= pd.read_csv("data_vegetals.csv")

VÃ©rifier les dimensions de notre DataFrame :

In [11]:
data.shape

# Renvoi un tuple dans lequel est affichÃ© le nombre de lignes = 86226, et le nombre de colonnes = 14

(86226, 14)

Voir les diffÃ©rentes colonnes :

In [10]:
data.columns

Index(['Domain Code', 'Domain', 'Area Code (M49)', 'Area', 'Element Code',
       'Element', 'Item Code (FAO)', 'Item', 'Year Code', 'Year', 'Unit',
       'Value', 'Flag', 'Flag Description'],
      dtype='object')

Afficher le dÃ©but de votre DataFrame :

In [15]:
data.head()

# Entre () on peut indiquer le nombre de lignes qui nous intÃ©resse (indices fonctionne Ã  peu prÃ¨s comme pour les listes)

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (FAO),Item,Year Code,Year,Unit,Value,Flag,Flag Description
0,FBS,Food Balances (2010-),4,Afghanistan,645,Food supply quantity (kg/capita/yr),2511,Wheat and products,2018,2018,kg,162.62,E,Estimated value
1,FBS,Food Balances (2010-),4,Afghanistan,645,Food supply quantity (kg/capita/yr),2511,Wheat and products,2019,2019,kg,160.40,E,Estimated value
2,FBS,Food Balances (2010-),4,Afghanistan,664,Food supply (kcal/capita/day),2511,Wheat and products,2018,2018,kcal/cap/d,1365.34,E,Estimated value
3,FBS,Food Balances (2010-),4,Afghanistan,664,Food supply (kcal/capita/day),2511,Wheat and products,2019,2019,kcal/cap/d,1346.93,E,Estimated value
4,FBS,Food Balances (2010-),4,Afghanistan,674,Protein supply quantity (g/capita/day),2511,Wheat and products,2018,2018,g/cap/d,41.23,E,Estimated value
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86220,FBS,Food Balances (2010-),716,Zimbabwe,664,Food supply (kcal/capita/day),2658,"Beverages, Alcoholic",2018,2018,kcal/cap/d,28.44,E,Estimated value
86221,FBS,Food Balances (2010-),716,Zimbabwe,664,Food supply (kcal/capita/day),2658,"Beverages, Alcoholic",2019,2019,kcal/cap/d,27.22,E,Estimated value
86222,FBS,Food Balances (2010-),716,Zimbabwe,674,Protein supply quantity (g/capita/day),2658,"Beverages, Alcoholic",2018,2018,g/cap/d,0.03,E,Estimated value
86223,FBS,Food Balances (2010-),716,Zimbabwe,674,Protein supply quantity (g/capita/day),2658,"Beverages, Alcoholic",2019,2019,g/cap/d,0.03,E,Estimated value
86224,FBS,Food Balances (2010-),716,Zimbabwe,684,Fat supply quantity (g/capita/day),2658,"Beverages, Alcoholic",2018,2018,g/cap/d,0.22,E,Estimated value

Si certaines des colonnes ne nous intÃ©resse pas forcÃ©ment on va pouvoir les Ã©liminer :

(imaginons que les colonnes 'Domain Code' et 'Domain' ne nous intÃ©resse pas)

In [30]:
data = pd.read_csv("data_vegetals.csv")
data = data.drop(["Domain", "Domain Code"], axis=1)
data.head()

,Area Code (M49),Area,Element Code,Element,Item Code (FAO),Item,Year Code,Year,Unit,Value,Flag,Flag Description
0,4,Afghanistan,645,Food supply quantity (kg/capita/yr),2511,Wheat and products,2018,2018,kg,162.62,E,Estimated value
1,4,Afghanistan,645,Food supply quantity (kg/capita/yr),2511,Wheat and products,2019,2019,kg,160.40,E,Estimated value
2,4,Afghanistan,664,Food supply (kcal/capita/day),2511,Wheat and products,2018,2018,kcal/cap/d,1365.34,E,Estimated value
3,4,Afghanistan,664,Food supply (kcal/capita/day),2511,Wheat and products,2019,2019,kcal/cap/d,1346.93,E,Estimated value
4,4,Afghanistan,674,Protein supply quantity (g/capita/day),2511,Wheat and products,2018,2018,g/cap/d,41.23,E,Estimated value

Produire les statistiques de bases pour nos colonnes :

In [33]:
data.describe()

,Area Code (M49),Element Code,Item Code (FAO),Year Code,Year,Value
count,86226.000000,86226.000000,86226.000000,86226.000000,86226.000000,86226.000000
mean,425.578515,666.764630,2589.954086,2018.509452,2018.509452,12.414431
std,250.537023,14.405249,55.720992,0.499914,0.499914,62.848062
min,4.000000,645.000000,2511.000000,2018.000000,2018.000000,0.000000
25%,204.000000,664.000000,2547.000000,2018.000000,2018.000000,0.000000
50%,418.000000,674.000000,2580.000000,2019.000000,2019.000000,0.170000
75%,642.000000,684.000000,2620.000000,2019.000000,2019.000000,2.770000
max,894.000000,684.000000,2807.000000,2019.000000,2019.000000,1744.850000

Le 'count' (ci-haut) indique le nombre de ligne. Ici dans chaque colonnes, on voit que le nombre de colonnes est identique. 86226 dans notre cas.

Si dans une des colonnes (par exemple: prenons la colonne 'Value') le nombre de lignes Ã©tait infÃ©rieur Ã  86226 ici.\
Ceci nous indique qu'il nous manque des donnÃ©es concernant 'Value'. 

Et quand il nous manque des donnÃ©es, c'est donc difficile de faire de l'analyse de donnÃ©es.

Dans ces situations, on 2 options :

OPTION 1 :\
Utiliser la fonction fillna() pour remplacer les donnÃ©es manquantes par une valeur par dÃ©faut.\
Par exemple, on pourrait dire que quand il nous manque une donnÃ©e, on pourrait tout simplement remplacer Ã§a par une moyenne

--> *Ã‡a peut Ãªtre une bonne option MAIS ATTENTION il faut garder Ã  l'esprit que Ã§a va corrompre notre dataset du coup on peut opter pour l'OPTION 2*

In [37]:
data.fillna(data["Value"].mean())

,Area Code (M49),Area,Element Code,Element,Item Code (FAO),Item,Year Code,Year,Unit,Value,Flag,Flag Description
0,4,Afghanistan,645,Food supply quantity (kg/capita/yr),2511,Wheat and products,2018,2018,kg,162.62,E,Estimated value
1,4,Afghanistan,645,Food supply quantity (kg/capita/yr),2511,Wheat and products,2019,2019,kg,160.40,E,Estimated value
2,4,Afghanistan,664,Food supply (kcal/capita/day),2511,Wheat and products,2018,2018,kcal/cap/d,1365.34,E,Estimated value
3,4,Afghanistan,664,Food supply (kcal/capita/day),2511,Wheat and products,2019,2019,kcal/cap/d,1346.93,E,Estimated value
4,4,Afghanistan,674,Protein supply quantity (g/capita/day),2511,Wheat and products,2018,2018,g/cap/d,41.23,E,Estimated value
...,...,...,...,...,...,...,...,...,...,...,...,...
86221,716,Zimbabwe,664,Food supply (kcal/capita/day),2658,"Beverages, Alcoholic",2019,2019,kcal/cap/d,27.22,E,Estimated value
86222,716,Zimbabwe,674,Protein supply quantity (g/capita/day),2658,"Beverages, Alcoholic",2018,2018,g/cap/d,0.03,E,Estimated value
86223,716,Zimbabwe,674,Protein supply quantity (g/capita/day),2658,"Beverages, Alcoholic",2019,2019,g/cap/d,0.03,E,Estimated value
86224,716,Zimbabwe,684,Fat supply quantity (g/capita/day),2658,"Beverages, Alcoholic",2018,2018,g/cap/d,0.22,E,Estimated value
86225,716,Zimbabwe,684,Fat supply quantity (g/capita/day),2658,"Beverages, Alcoholic",2019,2019,g/cap/d,0.21,E,Estimated value

OPTION 2 :
Ã‰liminer les lignes dans lesquelles ils nous manquent des donnÃ©es\

--> *Parfois il vaut mieux perdre un peu de donnÃ©es plutÃ´t que de corrompre la rÃ©alitÃ© des choses*

In [40]:
data.dropna(axis=0)

,Area Code (M49),Area,Element Code,Element,Item Code (FAO),Item,Year Code,Year,Unit,Value,Flag,Flag Description
0,4,Afghanistan,645,Food supply quantity (kg/capita/yr),2511,Wheat and products,2018,2018,kg,162.62,E,Estimated value
1,4,Afghanistan,645,Food supply quantity (kg/capita/yr),2511,Wheat and products,2019,2019,kg,160.40,E,Estimated value
2,4,Afghanistan,664,Food supply (kcal/capita/day),2511,Wheat and products,2018,2018,kcal/cap/d,1365.34,E,Estimated value
3,4,Afghanistan,664,Food supply (kcal/capita/day),2511,Wheat and products,2019,2019,kcal/cap/d,1346.93,E,Estimated value
4,4,Afghanistan,674,Protein supply quantity (g/capita/day),2511,Wheat and products,2018,2018,g/cap/d,41.23,E,Estimated value
...,...,...,...,...,...,...,...,...,...,...,...,...
86221,716,Zimbabwe,664,Food supply (kcal/capita/day),2658,"Beverages, Alcoholic",2019,2019,kcal/cap/d,27.22,E,Estimated value
86222,716,Zimbabwe,674,Protein supply quantity (g/capita/day),2658,"Beverages, Alcoholic",2018,2018,g/cap/d,0.03,E,Estimated value
86223,716,Zimbabwe,674,Protein supply quantity (g/capita/day),2658,"Beverages, Alcoholic",2019,2019,g/cap/d,0.03,E,Estimated value
86224,716,Zimbabwe,684,Fat supply quantity (g/capita/day),2658,"Beverages, Alcoholic",2018,2018,g/cap/d,0.22,E,Estimated value
86225,716,Zimbabwe,684,Fat supply quantity (g/capita/day),2658,"Beverages, Alcoholic",2019,2019,g/cap/d,0.21,E,Estimated value

Maintenant, mettons qu'on veux savoir combien il y a de produits dans les diffÃ©rents types d'Ã©lÃ©ments (= disponibilitÃ© alimentaire en kg, disponibilitÃ© alimentaire en kcal, disponibilitÃ© alimentaire en protÃ©ines, disponibilitÃ© alimentaire en matiÃ¨re grasse).

On va donc utiliser la fonction 'value_counts()'

In [41]:
data["Element"].value_counts()

Element
Food supply (kcal/capita/day)             21571
Protein supply quantity (g/capita/day)    21571
Fat supply quantity (g/capita/day)        21571
Food supply quantity (kg/capita/yr)       21513
Name: count, dtype: int64

Maintenant avec ces donnÃ©es, nous allons crÃ©er notre premier graphique (simple)

In [43]:
data["Element"].value_counts().plot.bar()

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.